kind: pipeline
name: publish

steps:
- name: flake8
  image: alpine/flake8:3.7.7
  commands:
  - flake8

- name: build base docker image
  image: plugins/docker
  settings:
    repo: liquidinvestigations/hoover-snoop2
    auto_tag: true
    auto_tag_suffix: base
    dockerfile: Dockerfile.base
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
    branch:
    - master

- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: liquidinvestigations/hoover-snoop2
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: liquidinvestigations/hoover-snoop2
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: test

depends_on:
- publish

services:
- name: snoop-rabbitmq
  image: rabbitmq:3.7.3
  volumes:
  - name: rabbit-v
    path: /var/lib/rabbitmq

- name: snoop-tika
  image: logicalspark/docker-tikaserver

- name: search-es
  image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
  environment:
    discovery.type: single-node
  volumes:
  - name: es-v
    path: /var/lib/elasticsearch/data

- name: snoop-pg
  image: postgres:12.2
  environment:
    POSTGRES_USER: snoop
    POSTGRES_DATABASE: snoop
    POSTGRES_PASSWORD: snoop
  volumes:
  - name: pg-v
    path: /var/lib/postgresql/data

steps:
- name: download testdata
  image: alpine/git:1.0.7
  volumes:
  - name: test-collections-v
    path: /testdata
  commands:
  - cd /testdata
  - git clone https://github.com/hoover/testdata .

- name: run tests
  image: liquidinvestigations/hoover-snoop2:${DRONE_COMMIT_BRANCH}
  pull: always
  volumes:
  - name: test-collections-v
    path: /opt/hoover/collections/testdata
  environment:
    WAIT_HOSTS: search-es:9200, snoop-pg:5432, snoop-tika:9998
    WAIT_HOSTS_TIMEOUT: 60
    SNOOP_DB: "postgresql://snoop:snoop@snoop-pg:5432/snoop"
    SNOOP_COLLECTIONS: '[{"name": "testdata", "process": true}]'
    SNOOP_AMQP_URL: "amqp://snoop-rabbitmq"
    SNOOP_TIKA_URL: "http://snoop-tika:9998"
    SNOOP_ES_URL: "http://search-es:9200"
    SNOOP_COLLECTION_ROOT: "/opt/hoover/collections"
    SNOOP_BLOB_STORAGE: "/opt/hoover/snoop/blobs"
    USER_MODE: "TEST"
  commands:
  - whoami
  - cd /opt/hoover/snoop
  - chown -R 666:666 /opt/hoover/collections
  - py.test -vv
  trigger:
    events:
    - push

volumes:
- name: test-collections-v
  temp: {}
- name: es-v
  temp: {}
- name: pg-v
  temp: {}

---
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password
