language: python
python:
  - "3.6"
addons:
  postgresql: "9.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y p7zip-full

install:
  - wget -nc http://archive.apache.org/dist/tika/tika-server-1.17.jar
  - pip install -r requirements.txt
  - git clone https://github.com/hoover/testdata.git

env:
  - SNOOP_TESTDATA=testdata

before_script:
  - java -jar tika-server-1.17.jar &
  - sleep 5

script:
  - py.test

notifications:
  email: false
