language: python
python:
  - "3.6"
addons:
  postgresql: "9.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y p7zip-full
  - sudo apt-get install -qq automake libtool make python zlib1g-dev
  - git clone https://github.com/hoover/magic-definitions.git
  - ( cd magic-definitions && ./build.sh && cp magic.mgc .. )
  - PATH=`pwd`/magic-definitions/file/bin:$PATH file -m magic.mgc --version

install:
  - wget -nc http://archive.apache.org/dist/tika/tika-server-1.17.jar
  - pip install -r requirements.txt
  - git clone https://github.com/hoover/testdata.git

env:
  - SNOOP_TESTDATA=testdata

before_script:
  - java -jar tika-server-1.17.jar &
  - sleep 5

script:
  - ls `pwd`/magic-definitions/file/bin/file
  - PATH=`pwd`/magic-definitions/file/bin:$PATH file -k -m magic.mgc magic-definitions/flie/bin/file
  - PATH=`pwd`/magic-definitions/file/bin:$PATH py.test

notifications:
  email: false
