services:
  - docker

install:
  - git clone https://github.com/hoover/docker-setup.git
  - cd docker-setup
  - mkdir -p volumes volumes/metrics volumes/metrics/users collections volumes/search-es-snapshots volumes/search-es/data
  - chmod 777 volumes/search-es-snapshots volumes/search-es/data
  - docker build .. --tag snoop2-testing
  - cp ../testsuite/docker-compose.override.travis-snoop2.yml docker-compose.override.yml
  - docker-compose up -d
  - git clone https://github.com/hoover/testdata collections/testdata

script:
  - docker-compose run --rm snoop bash -c '/wait && py.test -vv --ignore=docker-setup'

notifications:
  email: false
