services:
  - docker

install:
  - '[[ "$TRAVIS_PULL_REQUEST_BRANCH" = "es6" ]] && (git clone https://github.com/jarib/docker-setup.git && cd docker-setup && git checkout es6 && cd -) || true'
  - '[[ "$TRAVIS_PULL_REQUEST_BRANCH" != "es6" ]] && (git clone https://github.com/hoover/docker-setup.git) || true'
  - cd docker-setup
  - mkdir -p volumes volumes/metrics volumes/metrics/users collections volumes/search-es-snapshots volumes/search-es/data
  - chmod 777 volumes/search-es-snapshots volumes/search-es/data
  - docker build .. --tag snoop2-testing
  - cp ../testsuite/docker-compose.override.travis-snoop2.yml docker-compose.override.yml
  - cp snoop.testing.env snoop.env
  - cp search.testing.env search.env
  - docker-compose up -d
  - git clone https://github.com/hoover/testdata collections/testdata
script:
  - docker-compose run --rm snoop bash -c '/wait && py.test -v'

notifications:
  email: false
