services:
  - docker

install:
  - git clone https://github.com/hoover/docker-setup.git
  - cd docker-setup
  - mkdir volumes volumes/metrics volumes/metrics/users collections
  - docker build .. --tag snoop2-testing
  - cp ../testsuite/docker-compose.override.travis-snoop2.yml docker-compose.override.yml
  - cp snoop.testing.env snoop.env
  - cp search.testing.env search.env
  - docker-compose up -d
  - git clone https://github.com/hoover/testdata collections/testdata

script:
  - docker-compose run --rm snoop bash -c 'sleep 15 && py.test -k "not test_unarchive_pst"'

notifications:
  email: false
