services:
  - docker

install:
  - '[[ "$TRAVIS_BRANCH" = "master" ]] && (git clone https://github.com/hoover/docker-setup.git) || true'
  - '[[ "$TRAVIS_BRANCH" = "es6" ]] && (git clone https://github.com/jarib/docker-setup.git && cd docker-setup && git checkout es6 && cd -) || true'
  - cd docker-setup
  - mkdir volumes volumes/metrics volumes/metrics/users collections volumes/search-es-snapshots
  - chmod 777 volumes/search-es-snapshots
  - docker build .. --tag snoop2-testing
  - cp ../testsuite/docker-compose.override.travis-snoop2.yml docker-compose.override.yml
  - cp snoop.testing.env snoop.env
  - cp search.testing.env search.env
  - docker-compose up -d
  - git clone https://github.com/hoover/testdata collections/testdata

script:
  - docker-compose run --rm snoop bash -c 'sleep 15 && py.test -v'

notifications:
  email: false
